using System.ComponentModel.DataAnnotations;
using Autodesk.Mcp.Shared.Contracts;
using Autodesk.Mcp.Shared.Enums;
using Autodesk.Mcp.Shared.Schemas;

namespace Autodesk.Mcp.Shared.Dtos;

/// <summary>
/// The immutable runtime description of one tool. Manifests are generated by the bridge at startup
/// (reflection over tool classes + NJsonSchema over DTOs) and served to the MCP server via
/// <c>tools/list</c>; the server registers each manifest as an MCP tool without any compile-time
/// knowledge of the product.
/// </summary>
public sealed record ToolManifest
{
    /// <summary>The stable machine identifier used on the wire (for example <c>list_alignments</c>).</summary>
    [Required]
    public string Name { get; init; } = string.Empty;

    /// <summary>Human-friendly label shown to users (for example <c>List Alignments</c>).</summary>
    [Required]
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>Markdown-capable description of what the tool does.</summary>
    [Required]
    public string Description { get; init; } = string.Empty;

    /// <summary>The functional category the tool belongs to.</summary>
    public ToolCategory Category { get; init; } = ToolCategory.Unknown;

    /// <summary>Semantic version of this tool contract; increments on any schema or behavior change.</summary>
    public VersionInformation Version { get; init; } = VersionInformation.Empty;

    /// <summary>The permission level required to invoke this tool.</summary>
    public ToolPermission Permission { get; init; } = ToolPermission.Unknown;

    /// <summary>The risk level associated with invoking this tool.</summary>
    public ToolRisk Risk { get; init; } = ToolRisk.Unknown;

    /// <summary>Maximum execution time in milliseconds before the bridge cancels the tool.</summary>
    [Range(1, int.MaxValue)]
    public int TimeoutMilliseconds { get; init; } = ProtocolConstants.DefaultToolTimeoutMilliseconds;

    /// <summary>True when the tool emits <c>$/progress</c> notifications during execution.</summary>
    public bool SupportsProgress { get; init; }

    /// <summary>True when the tool cooperates with <c>$/cancel</c> notifications.</summary>
    public bool SupportsCancellation { get; init; }

    /// <summary>True when the tool can stream partial results before completion.</summary>
    public bool SupportsStreaming { get; init; }

    /// <summary>JSON Schema describing valid inputs; generated by NJsonSchema from the input DTO.</summary>
    [Required]
    public JsonSchemaDocument InputSchema { get; init; } = JsonSchemaDocument.Empty;

    /// <summary>JSON Schema describing the output; generated by NJsonSchema from the output DTO.</summary>
    [Required]
    public JsonSchemaDocument OutputSchema { get; init; } = JsonSchemaDocument.Empty;

    /// <summary>Optional worked examples of inputs and outputs.</summary>
    public IReadOnlyList<ToolExample> Examples { get; init; } = Array.Empty<ToolExample>();

    /// <summary>Free-form classification tags used for filtering and discovery.</summary>
    public IReadOnlyList<string> Tags { get; init; } = Array.Empty<string>();

    /// <summary>True when the tool is deprecated and should be hidden from new clients.</summary>
    public bool Deprecated { get; init; }
}
